services:
  db:
    image: postgres:16.2
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./backups:/backups
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - app-network

  #frontend:
  #  build:
  #    context: ./frontend
  #    dockerfile: build/Dockerfile
  #  volumes:
  #    - ./code:/var/www/frontend
  #    - ./backups:/backups
  #  command: npm run dev

  nginx:
    image: nginx:1.25.4-alpine
    environment:
      TZ: "Europe/Moscow"
    env_file:
      - .env
    volumes:
      - ./backend/code:/var/www/backend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "${WEB_PORT}:80"
    networks:
      - app-network


  app:
    build:
      context: ./backend/
      dockerfile: ./build/Dockerfile
    volumes:
      - ./backend/code:/var/www/backend
    env_file:
      - .env
    networks:
      - app-network

  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v5
    volumes:
      - ./centrifugo/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - ${CENTRIFUGO_PORT}:8000
    env_file:
      - .env
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
